---
- hosts: all
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: Update apt
      apt: update_cache=yes

    - name: Install nginx
      apt: name=nginx state=latest

    - name: Copy nginx configuration to server
      template:
        src: templates/homepage.conf.j2
        dest: /etc/nginx/sites-enabled/homepage.conf
        owner: gabriel
        mode: 0755

    - name: Allow access to http port
      ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Restart nginx
      service: name=nginx state=restarted

    - name: Deploy homepage
      become: false
      synchronize: 
        src: ../site
        dest: "{{ doc_root }}"

